name: workflow 1
on: push


jobs:
    Rana:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome 
              run: |
                echo "Hello world"
                sudo apt update -y
                sudo apt install cowsay -y
                cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
                cat dragon.txt
    Rana2:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v4
            - name: checkout 
              run: |
               ls -ltrah
               cat README.md
               sleep 10

        